/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/node.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/node.pb-c.h"
void   node__init
                     (Node         *message)
{
  static const Node init_value = NODE__INIT;
  *message = init_value;
}
size_t node__get_packed_size
                     (const Node *message)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t node__pack
                     (const Node *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t node__pack_to_buffer
                     (const Node *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &node__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Node *
       node__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Node *)
     protobuf_c_message_unpack (&node__descriptor,
                                allocator, len, data);
}
void   node__free_unpacked
                     (Node *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &node__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tree_arrayed__init
                     (TreeArrayed         *message)
{
  static const TreeArrayed init_value = TREE_ARRAYED__INIT;
  *message = init_value;
}
size_t tree_arrayed__get_packed_size
                     (const TreeArrayed *message)
{
  assert(message->base.descriptor == &tree_arrayed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tree_arrayed__pack
                     (const TreeArrayed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tree_arrayed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tree_arrayed__pack_to_buffer
                     (const TreeArrayed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tree_arrayed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TreeArrayed *
       tree_arrayed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TreeArrayed *)
     protobuf_c_message_unpack (&tree_arrayed__descriptor,
                                allocator, len, data);
}
void   tree_arrayed__free_unpacked
                     (TreeArrayed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tree_arrayed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor node__field_descriptors[2] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Node, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Node, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned node__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = ip */
};
static const ProtobufCIntRange node__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor node__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Node",
  "Node",
  "Node",
  "",
  sizeof(Node),
  2,
  node__field_descriptors,
  node__field_indices_by_name,
  1,  node__number_ranges,
  (ProtobufCMessageInit) node__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tree_arrayed__field_descriptors[2] =
{
  {
    "length",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(TreeArrayed, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nodes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TreeArrayed, n_nodes),
    offsetof(TreeArrayed, nodes),
    &node__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tree_arrayed__field_indices_by_name[] = {
  0,   /* field[0] = length */
  1,   /* field[1] = nodes */
};
static const ProtobufCIntRange tree_arrayed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tree_arrayed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TreeArrayed",
  "TreeArrayed",
  "TreeArrayed",
  "",
  sizeof(TreeArrayed),
  2,
  tree_arrayed__field_descriptors,
  tree_arrayed__field_indices_by_name,
  1,  tree_arrayed__number_ranges,
  (ProtobufCMessageInit) tree_arrayed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
